### ISSUE TITLE
Internal server error on 1st login attempt

### ISSUE THREAD

**Issue by msris108** [msris108/aspire-hackathon-solution#5]
logstash - Internal Server Error: /auth/email/
backend          | Traceback (most recent call last):
backend          |   File "/app/drfpasswordless/serializers.py", line 50, in validate
backend          |     user = User.objects.get(**{self.alias_type+'__iexact': alias})
backend          |   File "/usr/local/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
backend          |     return getattr(self.get_queryset(), name)(*args, **kwargs)
backend          |   File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 650, in get
backend          |     raise self.model.DoesNotExist(
backend          | backend.models.CustomUser.DoesNotExist: CustomUser matching query does not exist.

Subsequent logins seem to be working fine.

**Comment by msris108** [comment]
temporary solution added.
